"""EvalSim — closed-loop simulation-evaluation platform.

The top-level API re-exports the stable data contracts. Implemented deeper layers use
their focused namespaces (for example, ``evalsim.sources``, ``evalsim.simulators``, and
``evalsim.rollout``) so the contract surface remains explicit.
"""
from .contracts import (
    Agent,
    AgentFrame,
    AgentType,
    CounterfactualPair,
    EgoInterventionSpec,
    EgoTrajectoryPlan,
    FeasibilityAudit,
    HistoryOnlyPolicyContext,
    HistoryOnlyPolicyObservation,
    HistoryOnlySimulatorPolicy,
    MapPolyline,
    MapType,
    Metric,
    MetricEligibility,
    MetricResult,
    MetricSpec,
    InterventionEligibility,
    PairedMetric,
    PairedMetricResult,
    PolicyMetadata,
    PolicyObservation,
    PolicyStep,
    PrivilegedPolicyContext,
    PrivilegedSimulatorPolicy,
    Rollout,
    RunManifest,
    Scenario,
    SimulatorPolicy,
    evaluate_paired_metric,
    rollout_from_parquet,
    rollout_to_parquet,
    scenario_from_parquet,
    scenario_to_parquet,
)

__version__ = "0.1.0"

__all__ = [
    "Agent",
    "AgentFrame",
    "AgentType",
    "CounterfactualPair",
    "EgoInterventionSpec",
    "EgoTrajectoryPlan",
    "FeasibilityAudit",
    "HistoryOnlyPolicyContext",
    "HistoryOnlyPolicyObservation",
    "HistoryOnlySimulatorPolicy",
    "MapPolyline",
    "MapType",
    "Metric",
    "MetricEligibility",
    "MetricResult",
    "MetricSpec",
    "InterventionEligibility",
    "PairedMetric",
    "PairedMetricResult",
    "PolicyMetadata",
    "PolicyObservation",
    "PolicyStep",
    "PrivilegedPolicyContext",
    "PrivilegedSimulatorPolicy",
    "Rollout",
    "RunManifest",
    "Scenario",
    "SimulatorPolicy",
    "evaluate_paired_metric",
    "rollout_from_parquet",
    "rollout_to_parquet",
    "scenario_from_parquet",
    "scenario_to_parquet",
]
